[package]
name = "astra"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
astra-yaml = { path = "../../crates/astra-yaml" }
astra-connectors = { path = "../../crates/astra-connectors" }
